######################################################################
# 処理ID：PlstParamJsonToCsv
# 処理名：プリザンターのパラメータJSONファイルのCSV化
# 処理概要：
# 1. プリザンターのパラメータJSONファイルをCSV化する
######################################################################

######################################################################
# JSONファイル読込用の関数
######################################################################
function ReadJsonContent($fileName) {
    return (Get-Content $fileName -Encoding UTF8 | ConvertFrom-Json);
}

######################################################################
# CSVファイル書込用の関数
######################################################################
function WriteCsv($fileName, $parameterName, $parameterValue) {
    if ($parameterValue -eq $null) {
        $parameterValue = 'null';
    }
    elseif ($parameterValue -is [int]) {
        $parameterValue = $parameterValue;
    }
    elseif ($parameterValue -is [decimal]) {
        $parameterValue = $parameterValue;
    }
    elseif ($parameterValue -eq $true) {
        $parameterValue = 'true';
    }
    elseif ($parameterValue -eq $false) {
        $parameterValue = 'false';
    }
    elseif ($parameterValue -eq "") {
        $parameterValue = '""';
    }
    elseif ([String]::IsNullOrEmpty($parameterValue)) {
        $parameterValue = 'null';
    }
    else {
        $parameterValue = ($parameterValue).Replace('\','\\');
        $parameterValue = ($parameterValue).Replace('"Pleasanter.org"','\"Pleasanter.org\"');
        $parameterValue = '"' + $parameterValue + '"';
    }
    $fileName + ',' + $parameterName + ',' + $parameterValue >> C:\work\Output.csv;
}

######################################################################
# 1. プリザンターのパラメータJSONファイルをCSV化する
######################################################################
'FileName,ParameterName,ParameterValue' > C:\work\Output.csv;
$fileName = "Api.json";
$jsonContent = ReadJsonContent($fileName);
WriteCsv $fileName "Version" $jsonContent.Version;
WriteCsv $fileName "Enabled" $jsonContent.Enabled;
WriteCsv $fileName "PageSize" $jsonContent.PageSize;
WriteCsv $fileName "LimitPerSite" $jsonContent.LimitPerSite;
WriteCsv $fileName "Compatibility_1_3_12" $jsonContent.Compatibility_1_3_12;
$fileName = "Authentication.json";
$jsonContent = ReadJsonContent($fileName);
WriteCsv $fileName "Provider" $jsonContent.Provider;
WriteCsv $fileName "DsProvider" $jsonContent.DsProvider;
WriteCsv $fileName "ServiceId" $jsonContent.ServiceId;
WriteCsv $fileName "ExtensionUrl" $jsonContent.ExtensionUrl;
WriteCsv $fileName "RejectUnregisteredUser" $jsonContent.RejectUnregisteredUser;
WriteCsv $fileName "LdapParameters[0].LdapSearchRoot" $jsonContent.LdapParameters[0].LdapSearchRoot;
WriteCsv $fileName "LdapParameters[0].LdapSearchProperty" $jsonContent.LdapParameters[0].LdapSearchProperty;
WriteCsv $fileName "LdapParameters[0].LdapSearchPattern" $jsonContent.LdapParameters[0].LdapSearchPattern;
WriteCsv $fileName "LdapParameters[0].LdapLoginPattern" $jsonContent.LdapParameters[0].LdapLoginPattern;
WriteCsv $fileName "LdapParameters[0].LdapAuthenticationType" $jsonContent.LdapParameters[0].LdapAuthenticationType;
WriteCsv $fileName "LdapParameters[0].NetBiosDomainName" $jsonContent.LdapParameters[0].NetBiosDomainName;
WriteCsv $fileName "LdapParameters[0].LdapTenantId" $jsonContent.LdapParameters[0].LdapTenantId;
WriteCsv $fileName "LdapParameters[0].LdapDeptCode" $jsonContent.LdapParameters[0].LdapDeptCode;
WriteCsv $fileName "LdapParameters[0].LdapDeptCodePattern" $jsonContent.LdapParameters[0].LdapDeptCodePattern;
WriteCsv $fileName "LdapParameters[0].LdapDeptName" $jsonContent.LdapParameters[0].LdapDeptName;
WriteCsv $fileName "LdapParameters[0].LdapDeptNamePattern" $jsonContent.LdapParameters[0].LdapDeptNamePattern;
WriteCsv $fileName "LdapParameters[0].LdapUserCode" $jsonContent.LdapParameters[0].LdapUserCode;
WriteCsv $fileName "LdapParameters[0].LdapUserCodePattern" $jsonContent.LdapParameters[0].LdapUserCodePattern;
WriteCsv $fileName "LdapParameters[0].LdapFirstName" $jsonContent.LdapParameters[0].LdapFirstName;
WriteCsv $fileName "LdapParameters[0].LdapFirstNamePattern" $jsonContent.LdapParameters[0].LdapFirstNamePattern;
WriteCsv $fileName "LdapParameters[0].LdapLastName" $jsonContent.LdapParameters[0].LdapLastName;
WriteCsv $fileName "LdapParameters[0].LdapLastNamePattern" $jsonContent.LdapParameters[0].LdapLastNamePattern;
WriteCsv $fileName "LdapParameters[0].LdapMailAddress" $jsonContent.LdapParameters[0].LdapMailAddress;
WriteCsv $fileName "LdapParameters[0].LdapMailAddressPattern" $jsonContent.LdapParameters[0].LdapMailAddressPattern;
WriteCsv $fileName "LdapParameters[0].LdapSyncPageSize" $jsonContent.LdapParameters[0].LdapSyncPageSize;
WriteCsv $fileName "LdapParameters[0].LdapSyncPatterns[0]" $jsonContent.LdapParameters[0].LdapSyncPatterns[0];
WriteCsv $fileName "LdapParameters[0].LdapExcludeAccountDisabled" $jsonContent.LdapParameters[0].LdapExcludeAccountDisabled;
WriteCsv $fileName "LdapParameters[0].AutoDisable" $jsonContent.LdapParameters[0].AutoDisable;
WriteCsv $fileName "LdapParameters[0].AutoEnable" $jsonContent.LdapParameters[0].AutoEnable;
WriteCsv $fileName "LdapParameters[0].LdapSyncUser" $jsonContent.LdapParameters[0].LdapSyncUser;
WriteCsv $fileName "LdapParameters[0].LdapSyncPassword" $jsonContent.LdapParameters[0].LdapSyncPassword;
WriteCsv $fileName "SamlParameters.Attributes.Name" $jsonContent.SamlParameters.Attributes.Name;
WriteCsv $fileName "SamlParameters.Attributes.UserCode" $jsonContent.SamlParameters.Attributes.UserCode;
WriteCsv $fileName "SamlParameters.Attributes.Birthday" $jsonContent.SamlParameters.Attributes.Birthday;
WriteCsv $fileName "SamlParameters.Attributes.Gender" $jsonContent.SamlParameters.Attributes.Gender;
WriteCsv $fileName "SamlParameters.Attributes.Language" $jsonContent.SamlParameters.Attributes.Language;
WriteCsv $fileName "SamlParameters.Attributes.TimeZone" $jsonContent.SamlParameters.Attributes.TimeZone;
WriteCsv $fileName "SamlParameters.Attributes.TenantManager" $jsonContent.SamlParameters.Attributes.TenantManager;
WriteCsv $fileName "SamlParameters.Attributes.DeptCode" $jsonContent.SamlParameters.Attributes.DeptCode;
WriteCsv $fileName "SamlParameters.Attributes.Dept" $jsonContent.SamlParameters.Attributes.Dept;
WriteCsv $fileName "SamlParameters.Attributes.Body" $jsonContent.SamlParameters.Attributes.Body;
WriteCsv $fileName "SamlParameters.Attributes.MailAddress" $jsonContent.SamlParameters.Attributes.MailAddress;
WriteCsv $fileName "SamlParameters.SamlTenantId" $jsonContent.SamlParameters.SamlTenantId;
WriteCsv $fileName "SamlParameters.DisableOverwriteName" $jsonContent.SamlParameters.DisableOverwriteName;
WriteCsv $fileName "SamlParameters.SPOptions.EntityId" $jsonContent.SamlParameters.SPOptions.EntityId;
WriteCsv $fileName "SamlParameters.SPOptions.ReturnUrl" $jsonContent.SamlParameters.SPOptions.ReturnUrl;
WriteCsv $fileName "SamlParameters.SPOptions.AuthenticateRequestSigningBehavior" $jsonContent.SamlParameters.SPOptions.AuthenticateRequestSigningBehavior;
WriteCsv $fileName "SamlParameters.SPOptions.OutboundSigningAlgorithm" $jsonContent.SamlParameters.SPOptions.OutboundSigningAlgorithm;
WriteCsv $fileName "SamlParameters.SPOptions.MinIncomingSigningAlgorithm" $jsonContent.SamlParameters.SPOptions.MinIncomingSigningAlgorithm;
WriteCsv $fileName "SamlParameters.SPOptions.IgnoreMissingInResponseTo" $jsonContent.SamlParameters.SPOptions.IgnoreMissingInResponseTo;
WriteCsv $fileName "SamlParameters.SPOptions.PublicOrigin" $jsonContent.SamlParameters.SPOptions.PublicOrigin;
WriteCsv $fileName "SamlParameters.SPOptions.ServiceCertificates" $jsonContent.SamlParameters.SPOptions.ServiceCertificates;
WriteCsv $fileName "SamlParameters.IdentityProviders[0].EntityId" $jsonContent.SamlParameters.IdentityProviders[0].EntityId;
WriteCsv $fileName "SamlParameters.IdentityProviders[0].SignOnUrl" $jsonContent.SamlParameters.IdentityProviders[0].SignOnUrl;
WriteCsv $fileName "SamlParameters.IdentityProviders[0].LogoutUrl" $jsonContent.SamlParameters.IdentityProviders[0].LogoutUrl;
WriteCsv $fileName "SamlParameters.IdentityProviders[0].AllowUnsolicitedAuthnResponse" $jsonContent.SamlParameters.IdentityProviders[0].AllowUnsolicitedAuthnResponse;
WriteCsv $fileName "SamlParameters.IdentityProviders[0].Binding" $jsonContent.SamlParameters.IdentityProviders[0].Binding;
WriteCsv $fileName "SamlParameters.IdentityProviders[0].WantAuthnRequestsSigned" $jsonContent.SamlParameters.IdentityProviders[0].WantAuthnRequestsSigned;
WriteCsv $fileName "SamlParameters.IdentityProviders[0].DisableOutboundLogoutRequests" $jsonContent.SamlParameters.IdentityProviders[0].DisableOutboundLogoutRequests;
WriteCsv $fileName "SamlParameters.IdentityProviders[0].LoadMetadata" $jsonContent.SamlParameters.IdentityProviders[0].LoadMetadata;
WriteCsv $fileName "SamlParameters.IdentityProviders[0].MetadataLocation" $jsonContent.SamlParameters.IdentityProviders[0].MetadataLocation;
WriteCsv $fileName "SamlParameters.IdentityProviders[0].SigningCertificate.StoreName" $jsonContent.SamlParameters.IdentityProviders[0].SigningCertificate.StoreName;
WriteCsv $fileName "SamlParameters.IdentityProviders[0].SigningCertificate.StoreLocation" $jsonContent.SamlParameters.IdentityProviders[0].SigningCertificate.StoreLocation;
WriteCsv $fileName "SamlParameters.IdentityProviders[0].SigningCertificate.X509FindType" $jsonContent.SamlParameters.IdentityProviders[0].SigningCertificate.X509FindType;
WriteCsv $fileName "SamlParameters.IdentityProviders[0].SigningCertificate.FindValue" $jsonContent.SamlParameters.IdentityProviders[0].SigningCertificate.FindValue;
$fileName = "AutoTestSettings.json";
$jsonContent = ReadJsonContent($fileName);
WriteCsv $fileName "Url" $jsonContent.Url;
WriteCsv $fileName "BrowserType" $jsonContent.BrowserType;
WriteCsv $fileName "Width" $jsonContent.Width;
WriteCsv $fileName "Height" $jsonContent.Height;
WriteCsv $fileName "ScreenShot" $jsonContent.ScreenShot;
WriteCsv $fileName "ScreenShotPath" $jsonContent.ScreenShotPath;
WriteCsv $fileName "ResultsPath" $jsonContent.ResultsPath;
WriteCsv $fileName "LogFileName" $jsonContent.LogFileName;
WriteCsv $fileName "TimeoutSeconds" $jsonContent.TimeoutSeconds;
$fileName = "BackgroundService.json";
$jsonContent = ReadJsonContent($fileName);
WriteCsv $fileName "EnvironmentVariables" $jsonContent.EnvironmentVariables;
WriteCsv $fileName "Reminder" $jsonContent.Reminder;
WriteCsv $fileName "ReminderIgnoreConsecutiveExceptionCount" $jsonContent.ReminderIgnoreConsecutiveExceptionCount;
WriteCsv $fileName "SyncByLdap" $jsonContent.SyncByLdap;
WriteCsv $fileName "SyncByLdapTime[0]" $jsonContent.SyncByLdapTime[0];
WriteCsv $fileName "DeleteSysLogs" $jsonContent.DeleteSysLogs;
WriteCsv $fileName "DeleteSysLogsTime[0]" $jsonContent.DeleteSysLogsTime[0];
WriteCsv $fileName "DeleteTemporaryFiles" $jsonContent.DeleteTemporaryFiles;
WriteCsv $fileName "DeleteTemporaryFilesTime[0]" $jsonContent.DeleteTemporaryFilesTime[0];
WriteCsv $fileName "DeleteTrashBox" $jsonContent.DeleteTrashBox;
WriteCsv $fileName "DeleteTrashBoxTime[0]" $jsonContent.DeleteTrashBoxTime[0];
WriteCsv $fileName "DeleteTrashBoxRetentionPeriod" $jsonContent.DeleteTrashBoxRetentionPeriod;
$fileName = "BackgroundTask.json";
$jsonContent = ReadJsonContent($fileName);
WriteCsv $fileName "Enabled" $jsonContent.Enabled;
WriteCsv $fileName "Interval" $jsonContent.Interval;
WriteCsv $fileName "BackgroundTaskSpan" $jsonContent.BackgroundTaskSpan;
WriteCsv $fileName "CreateSearchIndexLot" $jsonContent.CreateSearchIndexLot;
$fileName = "BinaryStorage.json";
$jsonContent = ReadJsonContent($fileName);
WriteCsv $fileName "Provider" $jsonContent.Provider;
WriteCsv $fileName "Path" $jsonContent.Path;
WriteCsv $fileName "Attachments" $jsonContent.Attachments;
WriteCsv $fileName "Images" $jsonContent.Images;
WriteCsv $fileName "RestoreLocalFiles" $jsonContent.RestoreLocalFiles;
WriteCsv $fileName "LimitQuantity" $jsonContent.LimitQuantity;
WriteCsv $fileName "MinQuantity" $jsonContent.MinQuantity;
WriteCsv $fileName "MaxQuantity" $jsonContent.MaxQuantity;
WriteCsv $fileName "LimitSize" $jsonContent.LimitSize;
WriteCsv $fileName "MinSize" $jsonContent.MinSize;
WriteCsv $fileName "MaxSize" $jsonContent.MaxSize;
WriteCsv $fileName "LimitTotalSize" $jsonContent.LimitTotalSize;
WriteCsv $fileName "TotalMinSize" $jsonContent.TotalMinSize;
WriteCsv $fileName "TotalMaxSize" $jsonContent.TotalMaxSize;
WriteCsv $fileName "LocalFolderLimitSize" $jsonContent.LocalFolderLimitSize;
WriteCsv $fileName "LocalFolderMinSize" $jsonContent.LocalFolderMinSize;
WriteCsv $fileName "LocalFolderMaxSize" $jsonContent.LocalFolderMaxSize;
WriteCsv $fileName "LocalFolderLimitTotalSize" $jsonContent.LocalFolderLimitTotalSize;
WriteCsv $fileName "LocalFolderTotalMinSize" $jsonContent.LocalFolderTotalMinSize;
WriteCsv $fileName "LocalFolderTotalMaxSize" $jsonContent.LocalFolderTotalMaxSize;
WriteCsv $fileName "UseStorageSelect" $jsonContent.UseStorageSelect;
WriteCsv $fileName "DefaultBinaryStorageProvider" $jsonContent.DefaultBinaryStorageProvider;
WriteCsv $fileName "ImageLimitSize" $jsonContent.ImageLimitSize;
WriteCsv $fileName "ThumbnailLimitSize" $jsonContent.ThumbnailLimitSize;
WriteCsv $fileName "ThumbnailMinSize" $jsonContent.ThumbnailMinSize;
WriteCsv $fileName "ThumbnailMaxSize" $jsonContent.ThumbnailMaxSize;
$fileName = "Dashboard.json";
$jsonContent = ReadJsonContent($fileName);
WriteCsv $fileName "TimeLineItemCount" $jsonContent.TimeLineItemCount;
WriteCsv $fileName "TimeLineItemCountMin" $jsonContent.TimeLineItemCountMin;
WriteCsv $fileName "TimeLineItemCountMax" $jsonContent.TimeLineItemCountMax;
$fileName = "Deleted.json";
$jsonContent = ReadJsonContent($fileName);
WriteCsv $fileName "Restore" $jsonContent.Restore;
WriteCsv $fileName "PhysicalDelete" $jsonContent.PhysicalDelete;
$fileName = "General.json";
$jsonContent = ReadJsonContent($fileName);
WriteCsv $fileName "HtmlHeadKeywords" $jsonContent.HtmlHeadKeywords;
WriteCsv $fileName "HtmlHeadDescription" $jsonContent.HtmlHeadDescription;
WriteCsv $fileName "HtmlHeadViewport" $jsonContent.HtmlHeadViewport;
WriteCsv $fileName "HtmlLogoText" $jsonContent.HtmlLogoText;
WriteCsv $fileName "HtmlPortalUrl" $jsonContent.HtmlPortalUrl;
WriteCsv $fileName "HtmlApplicationBuildingGuideUrl" $jsonContent.HtmlApplicationBuildingGuideUrl;
WriteCsv $fileName "HtmlUserManualUrl" $jsonContent.HtmlUserManualUrl;
WriteCsv $fileName "HtmlBlogUrl" $jsonContent.HtmlBlogUrl;
WriteCsv $fileName "HtmlSupportUrl" $jsonContent.HtmlSupportUrl;
WriteCsv $fileName "HtmlContactUrl" $jsonContent.HtmlContactUrl;
WriteCsv $fileName "HtmlAGPLUrl" $jsonContent.HtmlAGPLUrl;
WriteCsv $fileName "HtmlEnterpriseEditionUrl" $jsonContent.HtmlEnterpriseEditionUrl;
WriteCsv $fileName "HtmlCasesUrl" $jsonContent.HtmlCasesUrl;
WriteCsv $fileName "DisplayLogoText" $jsonContent.DisplayLogoText;
WriteCsv $fileName "DisableAutoComplete" $jsonContent.DisableAutoComplete;
WriteCsv $fileName "SiteMenuHotSpan" $jsonContent.SiteMenuHotSpan;
WriteCsv $fileName "AnchorTargetBlank" $jsonContent.AnchorTargetBlank;
WriteCsv $fileName "LimitWarning1" $jsonContent.LimitWarning1;
WriteCsv $fileName "LimitWarning2" $jsonContent.LimitWarning2;
WriteCsv $fileName "LimitWarning3" $jsonContent.LimitWarning3;
WriteCsv $fileName "DeleteTempOldThan" $jsonContent.DeleteTempOldThan;
WriteCsv $fileName "DeleteHistoriesOldThan" $jsonContent.DeleteHistoriesOldThan;
WriteCsv $fileName "NearCompletionTimeBeforeDays" $jsonContent.NearCompletionTimeBeforeDays;
WriteCsv $fileName "NearCompletionTimeBeforeDaysMin" $jsonContent.NearCompletionTimeBeforeDaysMin;
WriteCsv $fileName "NearCompletionTimeBeforeDaysMax" $jsonContent.NearCompletionTimeBeforeDaysMax;
WriteCsv $fileName "NearCompletionTimeAfterDays" $jsonContent.NearCompletionTimeAfterDays;
WriteCsv $fileName "NearCompletionTimeAfterDaysMin" $jsonContent.NearCompletionTimeAfterDaysMin;
WriteCsv $fileName "NearCompletionTimeAfterDaysMax" $jsonContent.NearCompletionTimeAfterDaysMax;
WriteCsv $fileName "GridPageSize" $jsonContent.GridPageSize;
WriteCsv $fileName "GridPageSizeMin" $jsonContent.GridPageSizeMin;
WriteCsv $fileName "GridPageSizeMax" $jsonContent.GridPageSizeMax;
WriteCsv $fileName "AllowViewReset" $jsonContent.AllowViewReset;
WriteCsv $fileName "ExportOutputColumnMax" $jsonContent.ExportOutputColumnMax;
WriteCsv $fileName "ImportEncoding" $jsonContent.ImportEncoding;
WriteCsv $fileName "UpdatableImport" $jsonContent.UpdatableImport;
WriteCsv $fileName "AllowStandardExport" $jsonContent.AllowStandardExport;
WriteCsv $fileName "ImportMax" $jsonContent.ImportMax;
WriteCsv $fileName "ViewerSwitchingType" $jsonContent.ViewerSwitchingType;
WriteCsv $fileName "UseNegativeFilters" $jsonContent.UseNegativeFilters;
WriteCsv $fileName "AllowCopy" $jsonContent.AllowCopy;
WriteCsv $fileName "AllowReferenceCopy" $jsonContent.AllowReferenceCopy;
WriteCsv $fileName "CharToAddWhenCopying" $jsonContent.CharToAddWhenCopying;
WriteCsv $fileName "UpdateResponseType" $jsonContent.UpdateResponseType;
WriteCsv $fileName "SolutionBackupPath" $jsonContent.SolutionBackupPath;
WriteCsv $fileName "SolutionBackupExcludeDirectories" $jsonContent.SolutionBackupExcludeDirectories;
WriteCsv $fileName "SizeToUseTextArea" $jsonContent.SizeToUseTextArea;
WriteCsv $fileName "CompletionCode" $jsonContent.CompletionCode;
WriteCsv $fileName "CommentDisplayLimitHistories" $jsonContent.CommentDisplayLimitHistories;
WriteCsv $fileName "CommentDisplayLimit" $jsonContent.CommentDisplayLimit;
WriteCsv $fileName "WorkValueHeight" $jsonContent.WorkValueHeight;
WriteCsv $fileName "WorkValueTextTop" $jsonContent.WorkValueTextTop;
WriteCsv $fileName "ProgressRateWidth" $jsonContent.ProgressRateWidth;
WriteCsv $fileName "ProgressRateItemHeight" $jsonContent.ProgressRateItemHeight;
WriteCsv $fileName "ProgressRateTextTop" $jsonContent.ProgressRateTextTop;
WriteCsv $fileName "CalendarBegin" $jsonContent.CalendarBegin;
WriteCsv $fileName "CalendarEnd" $jsonContent.CalendarEnd;
WriteCsv $fileName "CalendarLimit" $jsonContent.CalendarLimit;
WriteCsv $fileName "CalendarYLimit" $jsonContent.CalendarYLimit;
WriteCsv $fileName "CrosstabBegin" $jsonContent.CrosstabBegin;
WriteCsv $fileName "CrosstabEnd" $jsonContent.CrosstabEnd;
WriteCsv $fileName "CrosstabXLimit" $jsonContent.CrosstabXLimit;
WriteCsv $fileName "CrosstabYLimit" $jsonContent.CrosstabYLimit;
WriteCsv $fileName "GanttLimit" $jsonContent.GanttLimit;
WriteCsv $fileName "GanttPeriodMin" $jsonContent.GanttPeriodMin;
WriteCsv $fileName "GanttPeriodMax" $jsonContent.GanttPeriodMax;
WriteCsv $fileName "BurnDownLimit" $jsonContent.BurnDownLimit;
WriteCsv $fileName "TimeSeriesLimit" $jsonContent.TimeSeriesLimit;
WriteCsv $fileName "KambanLimit" $jsonContent.KambanLimit;
WriteCsv $fileName "KambanXLimit" $jsonContent.KambanXLimit;
WriteCsv $fileName "KambanYLimit" $jsonContent.KambanYLimit;
WriteCsv $fileName "KambanMinColumns" $jsonContent.KambanMinColumns;
WriteCsv $fileName "KambanMaxColumns" $jsonContent.KambanMaxColumns;
WriteCsv $fileName "KambanColumns" $jsonContent.KambanColumns;
WriteCsv $fileName "ImageLibPageSize" $jsonContent.ImageLibPageSize;
WriteCsv $fileName "ImageLibPageSizeMin" $jsonContent.ImageLibPageSizeMin;
WriteCsv $fileName "ImageLibPageSizeMax" $jsonContent.ImageLibPageSizeMax;
WriteCsv $fileName "ImageSizeRegular" $jsonContent.ImageSizeRegular;
WriteCsv $fileName "ImageSizeThumbnail" $jsonContent.ImageSizeThumbnail;
WriteCsv $fileName "ImageSizeIcon" $jsonContent.ImageSizeIcon;
WriteCsv $fileName "ImageSizeLogo" $jsonContent.ImageSizeLogo;
WriteCsv $fileName "DropDownSearchPageSize" $jsonContent.DropDownSearchPageSize;
WriteCsv $fileName "SwitchTargetsLimit" $jsonContent.SwitchTargetsLimit;
WriteCsv $fileName "SeparateMin" $jsonContent.SeparateMin;
WriteCsv $fileName "SeparateMax" $jsonContent.SeparateMax;
WriteCsv $fileName "FirstDayOfWeek" $jsonContent.FirstDayOfWeek;
WriteCsv $fileName "FirstMonth" $jsonContent.FirstMonth;
WriteCsv $fileName "DateFilterMinSpan" $jsonContent.DateFilterMinSpan;
WriteCsv $fileName "DateFilterMaxSpan" $jsonContent.DateFilterMaxSpan;
WriteCsv $fileName "MinTime" $jsonContent.MinTime;
WriteCsv $fileName "MaxTime" $jsonContent.MaxTime;
WriteCsv $fileName "DateTimeStep" $jsonContent.DateTimeStep;
WriteCsv $fileName "HideCurrentTimeIcon" $jsonContent.HideCurrentTimeIcon;
WriteCsv $fileName "HideCurrentUserIcon" $jsonContent.HideCurrentUserIcon;
WriteCsv $fileName "HideCurrentDeptIcon" $jsonContent.HideCurrentDeptIcon;
$fileName = "GroupMembers.json";
$jsonContent = ReadJsonContent($fileName);
WriteCsv $fileName "DeptFormat" $jsonContent.DeptFormat;
WriteCsv $fileName "UserFormat" $jsonContent.UserFormat;
$fileName = "History.json";
$jsonContent = ReadJsonContent($fileName);
WriteCsv $fileName "Restore" $jsonContent.Restore;
WriteCsv $fileName "PhysicalDelete" $jsonContent.PhysicalDelete;
$fileName = "Locations.json";
$jsonContent = ReadJsonContent($fileName);
WriteCsv $fileName "TopUrl" $jsonContent.TopUrl;
WriteCsv $fileName "LoginAfterUrl" $jsonContent.LoginAfterUrl;
WriteCsv $fileName "LoginAfterUrlExcludePrivilegedUsers" $jsonContent.LoginAfterUrlExcludePrivilegedUsers;
$fileName = "Mail.json";
$jsonContent = ReadJsonContent($fileName);
WriteCsv $fileName "SmtpHost" $jsonContent.SmtpHost;
WriteCsv $fileName "SmtpPort" $jsonContent.SmtpPort;
WriteCsv $fileName "SmtpUserName" $jsonContent.SmtpUserName;
WriteCsv $fileName "SmtpPassword" $jsonContent.SmtpPassword;
WriteCsv $fileName "SmtpEnableSsl" $jsonContent.SmtpEnableSsl;
WriteCsv $fileName "ServerCertificateValidationCallback" $jsonContent.ServerCertificateValidationCallback;
WriteCsv $fileName "FixedFrom" $jsonContent.FixedFrom;
WriteCsv $fileName "AllowedFrom" $jsonContent.AllowedFrom;
WriteCsv $fileName "SupportFrom" $jsonContent.SupportFrom;
WriteCsv $fileName "InternalDomains" $jsonContent.InternalDomains;
WriteCsv $fileName "Encoding" $jsonContent.Encoding;
WriteCsv $fileName "ContentEncoding" $jsonContent.ContentEncoding;
$fileName = "Migration.json";
$jsonContent = ReadJsonContent($fileName);
WriteCsv $fileName "SourceConnectionString" $jsonContent.SourceConnectionString;
WriteCsv $fileName "ExcludeTables[0]" $jsonContent.ExcludeTables[0];
$fileName = "Mobile.json";
$jsonContent = ReadJsonContent($fileName);
WriteCsv $fileName "Responsive" $jsonContent.Responsive;
WriteCsv $fileName "SiteSettingsResponsive" $jsonContent.SiteSettingsResponsive;
$fileName = "NavigationMenus.json";
$jsonContent = ReadJsonContent($fileName);
WriteCsv $fileName "[0].ContainerId" $jsonContent[0].ContainerId;
WriteCsv $fileName "[0].MenuId" $jsonContent[0].MenuId;
WriteCsv $fileName "[0].Name" $jsonContent[0].Name;
WriteCsv $fileName "[0].Icon" $jsonContent[0].Icon;
WriteCsv $fileName "[0].LinkParams[0]" $jsonContent[0].LinkParams[0];
WriteCsv $fileName "[0].Function" $jsonContent[0].Function;
WriteCsv $fileName "[1].ContainerId" $jsonContent[1].ContainerId;
WriteCsv $fileName "[1].MenuId" $jsonContent[1].MenuId;
WriteCsv $fileName "[1].Name" $jsonContent[1].Name;
WriteCsv $fileName "[1].Icon" $jsonContent[1].Icon;
WriteCsv $fileName "[1].ChildMenus[0].MenuId" $jsonContent[1].ChildMenus[0].MenuId;
WriteCsv $fileName "[1].ChildMenus[0].Name" $jsonContent[1].ChildMenus[0].Name;
WriteCsv $fileName "[1].ChildMenus[0].Icon" $jsonContent[1].ChildMenus[0].Icon;
WriteCsv $fileName "[1].ChildMenus[0].Function" $jsonContent[1].ChildMenus[0].Function;
WriteCsv $fileName "[1].ChildMenus[1].MenuId" $jsonContent[1].ChildMenus[1].MenuId;
WriteCsv $fileName "[1].ChildMenus[1].Name" $jsonContent[1].ChildMenus[1].Name;
WriteCsv $fileName "[1].ChildMenus[1].Icon" $jsonContent[1].ChildMenus[1].Icon;
WriteCsv $fileName "[1].ChildMenus[1].Function" $jsonContent[1].ChildMenus[1].Function;
WriteCsv $fileName "[1].ChildMenus[2].MenuId" $jsonContent[1].ChildMenus[2].MenuId;
WriteCsv $fileName "[1].ChildMenus[2].Name" $jsonContent[1].ChildMenus[2].Name;
WriteCsv $fileName "[1].ChildMenus[2].Icon" $jsonContent[1].ChildMenus[2].Icon;
WriteCsv $fileName "[1].ChildMenus[2].Function" $jsonContent[1].ChildMenus[2].Function;
WriteCsv $fileName "[1].ChildMenus[3].MenuId" $jsonContent[1].ChildMenus[3].MenuId;
WriteCsv $fileName "[1].ChildMenus[3].Name" $jsonContent[1].ChildMenus[3].Name;
WriteCsv $fileName "[1].ChildMenus[3].Icon" $jsonContent[1].ChildMenus[3].Icon;
WriteCsv $fileName "[1].ChildMenus[3].Function" $jsonContent[1].ChildMenus[3].Function;
WriteCsv $fileName "[1].ChildMenus[4].MenuId" $jsonContent[1].ChildMenus[4].MenuId;
WriteCsv $fileName "[1].ChildMenus[4].Name" $jsonContent[1].ChildMenus[4].Name;
WriteCsv $fileName "[1].ChildMenus[4].Icon" $jsonContent[1].ChildMenus[4].Icon;
WriteCsv $fileName "[1].ChildMenus[4].Function" $jsonContent[1].ChildMenus[4].Function;
WriteCsv $fileName "[1].ChildMenus[5].MenuId" $jsonContent[1].ChildMenus[5].MenuId;
WriteCsv $fileName "[1].ChildMenus[5].Name" $jsonContent[1].ChildMenus[5].Name;
WriteCsv $fileName "[1].ChildMenus[5].Icon" $jsonContent[1].ChildMenus[5].Icon;
WriteCsv $fileName "[1].ChildMenus[5].Function" $jsonContent[1].ChildMenus[5].Function;
WriteCsv $fileName "[1].ChildMenus[6].MenuId" $jsonContent[1].ChildMenus[6].MenuId;
WriteCsv $fileName "[1].ChildMenus[6].Name" $jsonContent[1].ChildMenus[6].Name;
WriteCsv $fileName "[1].ChildMenus[6].Icon" $jsonContent[1].ChildMenus[6].Icon;
WriteCsv $fileName "[1].ChildMenus[6].Function" $jsonContent[1].ChildMenus[6].Function;
WriteCsv $fileName "[1].ChildMenus[7].MenuId" $jsonContent[1].ChildMenus[7].MenuId;
WriteCsv $fileName "[1].ChildMenus[7].Name" $jsonContent[1].ChildMenus[7].Name;
WriteCsv $fileName "[1].ChildMenus[7].Icon" $jsonContent[1].ChildMenus[7].Icon;
WriteCsv $fileName "[1].ChildMenus[7].Function" $jsonContent[1].ChildMenus[7].Function;
WriteCsv $fileName "[2].ContainerId" $jsonContent[2].ContainerId;
WriteCsv $fileName "[2].MenuId" $jsonContent[2].MenuId;
WriteCsv $fileName "[2].Name" $jsonContent[2].Name;
WriteCsv $fileName "[2].Icon" $jsonContent[2].Icon;
WriteCsv $fileName "[2].ChildMenus[0].MenuId" $jsonContent[2].ChildMenus[0].MenuId;
WriteCsv $fileName "[2].ChildMenus[0].Name" $jsonContent[2].ChildMenus[0].Name;
WriteCsv $fileName "[2].ChildMenus[0].Icon" $jsonContent[2].ChildMenus[0].Icon;
WriteCsv $fileName "[2].ChildMenus[0].LinkParams[0]" $jsonContent[2].ChildMenus[0].LinkParams[0];
WriteCsv $fileName "[2].ChildMenus[0].LinkParams[1]" $jsonContent[2].ChildMenus[0].LinkParams[1];
WriteCsv $fileName "[2].ChildMenus[0].LinkParams[2]" $jsonContent[2].ChildMenus[0].LinkParams[2];
WriteCsv $fileName "[2].ChildMenus[1].MenuId" $jsonContent[2].ChildMenus[1].MenuId;
WriteCsv $fileName "[2].ChildMenus[1].Name" $jsonContent[2].ChildMenus[1].Name;
WriteCsv $fileName "[2].ChildMenus[1].Icon" $jsonContent[2].ChildMenus[1].Icon;
WriteCsv $fileName "[2].ChildMenus[1].Function" $jsonContent[2].ChildMenus[1].Function;
WriteCsv $fileName "[2].ChildMenus[2].MenuId" $jsonContent[2].ChildMenus[2].MenuId;
WriteCsv $fileName "[2].ChildMenus[2].Name" $jsonContent[2].ChildMenus[2].Name;
WriteCsv $fileName "[2].ChildMenus[2].Icon" $jsonContent[2].ChildMenus[2].Icon;
WriteCsv $fileName "[2].ChildMenus[2].Function" $jsonContent[2].ChildMenus[2].Function;
WriteCsv $fileName "[2].ChildMenus[3].MenuId" $jsonContent[2].ChildMenus[3].MenuId;
WriteCsv $fileName "[2].ChildMenus[3].Name" $jsonContent[2].ChildMenus[3].Name;
WriteCsv $fileName "[2].ChildMenus[3].Icon" $jsonContent[2].ChildMenus[3].Icon;
WriteCsv $fileName "[2].ChildMenus[3].Function" $jsonContent[2].ChildMenus[3].Function;
WriteCsv $fileName "[2].ChildMenus[4].MenuId" $jsonContent[2].ChildMenus[4].MenuId;
WriteCsv $fileName "[2].ChildMenus[4].Name" $jsonContent[2].ChildMenus[4].Name;
WriteCsv $fileName "[2].ChildMenus[4].Icon" $jsonContent[2].ChildMenus[4].Icon;
WriteCsv $fileName "[2].ChildMenus[4].LinkParams[0]" $jsonContent[2].ChildMenus[4].LinkParams[0];
WriteCsv $fileName "[2].ChildMenus[4].LinkParams[1]" $jsonContent[2].ChildMenus[4].LinkParams[1];
WriteCsv $fileName "[2].ChildMenus[5].MenuId" $jsonContent[2].ChildMenus[5].MenuId;
WriteCsv $fileName "[2].ChildMenus[5].Name" $jsonContent[2].ChildMenus[5].Name;
WriteCsv $fileName "[2].ChildMenus[5].Icon" $jsonContent[2].ChildMenus[5].Icon;
WriteCsv $fileName "[2].ChildMenus[5].LinkParams[0]" $jsonContent[2].ChildMenus[5].LinkParams[0];
WriteCsv $fileName "[2].ChildMenus[6].MenuId" $jsonContent[2].ChildMenus[6].MenuId;
WriteCsv $fileName "[2].ChildMenus[6].Name" $jsonContent[2].ChildMenus[6].Name;
WriteCsv $fileName "[2].ChildMenus[6].Icon" $jsonContent[2].ChildMenus[6].Icon;
WriteCsv $fileName "[2].ChildMenus[6].LinkParams[0]" $jsonContent[2].ChildMenus[6].LinkParams[0];
WriteCsv $fileName "[2].ChildMenus[7].MenuId" $jsonContent[2].ChildMenus[7].MenuId;
WriteCsv $fileName "[2].ChildMenus[7].Name" $jsonContent[2].ChildMenus[7].Name;
WriteCsv $fileName "[2].ChildMenus[7].Icon" $jsonContent[2].ChildMenus[7].Icon;
WriteCsv $fileName "[2].ChildMenus[7].LinkParams[0]" $jsonContent[2].ChildMenus[7].LinkParams[0];
WriteCsv $fileName "[2].ChildMenus[8].MenuId" $jsonContent[2].ChildMenus[8].MenuId;
WriteCsv $fileName "[2].ChildMenus[8].Name" $jsonContent[2].ChildMenus[8].Name;
WriteCsv $fileName "[2].ChildMenus[8].Icon" $jsonContent[2].ChildMenus[8].Icon;
WriteCsv $fileName "[2].ChildMenus[8].LinkParams[0]" $jsonContent[2].ChildMenus[8].LinkParams[0];
WriteCsv $fileName "[2].ChildMenus[9].MenuId" $jsonContent[2].ChildMenus[9].MenuId;
WriteCsv $fileName "[2].ChildMenus[9].Name" $jsonContent[2].ChildMenus[9].Name;
WriteCsv $fileName "[2].ChildMenus[9].Icon" $jsonContent[2].ChildMenus[9].Icon;
WriteCsv $fileName "[2].ChildMenus[9].Function" $jsonContent[2].ChildMenus[9].Function;
WriteCsv $fileName "[2].ChildMenus[10].MenuId" $jsonContent[2].ChildMenus[10].MenuId;
WriteCsv $fileName "[2].ChildMenus[10].Name" $jsonContent[2].ChildMenus[10].Name;
WriteCsv $fileName "[2].ChildMenus[10].Icon" $jsonContent[2].ChildMenus[10].Icon;
WriteCsv $fileName "[2].ChildMenus[10].Function" $jsonContent[2].ChildMenus[10].Function;
WriteCsv $fileName "[2].ChildMenus[11].MenuId" $jsonContent[2].ChildMenus[11].MenuId;
WriteCsv $fileName "[2].ChildMenus[11].Name" $jsonContent[2].ChildMenus[11].Name;
WriteCsv $fileName "[2].ChildMenus[11].Icon" $jsonContent[2].ChildMenus[11].Icon;
WriteCsv $fileName "[2].ChildMenus[11].LinkParams[0]" $jsonContent[2].ChildMenus[11].LinkParams[0];
WriteCsv $fileName "[2].ChildMenus[12].MenuId" $jsonContent[2].ChildMenus[12].MenuId;
WriteCsv $fileName "[2].ChildMenus[12].Name" $jsonContent[2].ChildMenus[12].Name;
WriteCsv $fileName "[2].ChildMenus[12].Icon" $jsonContent[2].ChildMenus[12].Icon;
WriteCsv $fileName "[2].ChildMenus[12].LinkParams[0]" $jsonContent[2].ChildMenus[12].LinkParams[0];
WriteCsv $fileName "[2].ChildMenus[12].LinkParams[1]" $jsonContent[2].ChildMenus[12].LinkParams[1];
WriteCsv $fileName "[2].ChildMenus[12].LinkParams[2]" $jsonContent[2].ChildMenus[12].LinkParams[2];
WriteCsv $fileName "[3].ContainerId" $jsonContent[3].ContainerId;
WriteCsv $fileName "[3].MenuId" $jsonContent[3].MenuId;
WriteCsv $fileName "[3].Name" $jsonContent[3].Name;
WriteCsv $fileName "[3].Icon" $jsonContent[3].Icon;
WriteCsv $fileName "[3].ChildMenus[0].MenuId" $jsonContent[3].ChildMenus[0].MenuId;
WriteCsv $fileName "[3].ChildMenus[0].Name" $jsonContent[3].ChildMenus[0].Name;
WriteCsv $fileName "[3].ChildMenus[0].Icon" $jsonContent[3].ChildMenus[0].Icon;
WriteCsv $fileName "[3].ChildMenus[0].Url" $jsonContent[3].ChildMenus[0].Url;
WriteCsv $fileName "[3].ChildMenus[0].Target" $jsonContent[3].ChildMenus[0].Target;
WriteCsv $fileName "[3].ChildMenus[1].MenuId" $jsonContent[3].ChildMenus[1].MenuId;
WriteCsv $fileName "[3].ChildMenus[1].Name" $jsonContent[3].ChildMenus[1].Name;
WriteCsv $fileName "[3].ChildMenus[1].Icon" $jsonContent[3].ChildMenus[1].Icon;
WriteCsv $fileName "[3].ChildMenus[1].Url" $jsonContent[3].ChildMenus[1].Url;
WriteCsv $fileName "[3].ChildMenus[1].Target" $jsonContent[3].ChildMenus[1].Target;
WriteCsv $fileName "[3].ChildMenus[2].MenuId" $jsonContent[3].ChildMenus[2].MenuId;
WriteCsv $fileName "[3].ChildMenus[2].Name" $jsonContent[3].ChildMenus[2].Name;
WriteCsv $fileName "[3].ChildMenus[2].Icon" $jsonContent[3].ChildMenus[2].Icon;
WriteCsv $fileName "[3].ChildMenus[2].Url" $jsonContent[3].ChildMenus[2].Url;
WriteCsv $fileName "[3].ChildMenus[2].Target" $jsonContent[3].ChildMenus[2].Target;
WriteCsv $fileName "[3].ChildMenus[3].MenuId" $jsonContent[3].ChildMenus[3].MenuId;
WriteCsv $fileName "[3].ChildMenus[3].Name" $jsonContent[3].ChildMenus[3].Name;
WriteCsv $fileName "[3].ChildMenus[3].Icon" $jsonContent[3].ChildMenus[3].Icon;
WriteCsv $fileName "[3].ChildMenus[3].Url" $jsonContent[3].ChildMenus[3].Url;
WriteCsv $fileName "[3].ChildMenus[3].Target" $jsonContent[3].ChildMenus[3].Target;
WriteCsv $fileName "[3].ChildMenus[4].MenuId" $jsonContent[3].ChildMenus[4].MenuId;
WriteCsv $fileName "[3].ChildMenus[4].Name" $jsonContent[3].ChildMenus[4].Name;
WriteCsv $fileName "[3].ChildMenus[4].Icon" $jsonContent[3].ChildMenus[4].Icon;
WriteCsv $fileName "[3].ChildMenus[4].Url" $jsonContent[3].ChildMenus[4].Url;
WriteCsv $fileName "[3].ChildMenus[4].Target" $jsonContent[3].ChildMenus[4].Target;
WriteCsv $fileName "[3].ChildMenus[5].MenuId" $jsonContent[3].ChildMenus[5].MenuId;
WriteCsv $fileName "[3].ChildMenus[5].Name" $jsonContent[3].ChildMenus[5].Name;
WriteCsv $fileName "[3].ChildMenus[5].Icon" $jsonContent[3].ChildMenus[5].Icon;
WriteCsv $fileName "[3].ChildMenus[5].Url" $jsonContent[3].ChildMenus[5].Url;
WriteCsv $fileName "[3].ChildMenus[5].Target" $jsonContent[3].ChildMenus[5].Target;
WriteCsv $fileName "[3].ChildMenus[6].MenuId" $jsonContent[3].ChildMenus[6].MenuId;
WriteCsv $fileName "[3].ChildMenus[6].Name" $jsonContent[3].ChildMenus[6].Name;
WriteCsv $fileName "[3].ChildMenus[6].Icon" $jsonContent[3].ChildMenus[6].Icon;
WriteCsv $fileName "[3].ChildMenus[6].LinkParams[0]" $jsonContent[3].ChildMenus[6].LinkParams[0];
WriteCsv $fileName "[4].ContainerId" $jsonContent[4].ContainerId;
WriteCsv $fileName "[4].MenuId" $jsonContent[4].MenuId;
WriteCsv $fileName "[4].Name" $jsonContent[4].Name;
WriteCsv $fileName "[4].Id" $jsonContent[4].Id;
WriteCsv $fileName "[4].Icon" $jsonContent[4].Icon;
WriteCsv $fileName "[4].ChildMenus[0].MenuId" $jsonContent[4].ChildMenus[0].MenuId;
WriteCsv $fileName "[4].ChildMenus[0].Name" $jsonContent[4].ChildMenus[0].Name;
WriteCsv $fileName "[4].ChildMenus[0].Icon" $jsonContent[4].ChildMenus[0].Icon;
WriteCsv $fileName "[4].ChildMenus[0].LinkParams[0]" $jsonContent[4].ChildMenus[0].LinkParams[0];
WriteCsv $fileName "[4].ChildMenus[0].LinkParams[1]" $jsonContent[4].ChildMenus[0].LinkParams[1];
WriteCsv $fileName "[4].ChildMenus[1].MenuId" $jsonContent[4].ChildMenus[1].MenuId;
WriteCsv $fileName "[4].ChildMenus[1].Name" $jsonContent[4].ChildMenus[1].Name;
WriteCsv $fileName "[4].ChildMenus[1].Icon" $jsonContent[4].ChildMenus[1].Icon;
WriteCsv $fileName "[4].ChildMenus[1].Function" $jsonContent[4].ChildMenus[1].Function;
WriteCsv $fileName "[4].ChildMenus[2].MenuId" $jsonContent[4].ChildMenus[2].MenuId;
WriteCsv $fileName "[4].ChildMenus[2].Name" $jsonContent[4].ChildMenus[2].Name;
WriteCsv $fileName "[4].ChildMenus[2].Icon" $jsonContent[4].ChildMenus[2].Icon;
WriteCsv $fileName "[4].ChildMenus[2].LinkParams[0]" $jsonContent[4].ChildMenus[2].LinkParams[0];
WriteCsv $fileName "[4].ChildMenus[2].LinkParams[1]" $jsonContent[4].ChildMenus[2].LinkParams[1];
WriteCsv $fileName "[4].ChildMenus[2].LinkParams[2]" $jsonContent[4].ChildMenus[2].LinkParams[2];
WriteCsv $fileName "[4].ChildMenus[3].MenuId" $jsonContent[4].ChildMenus[3].MenuId;
WriteCsv $fileName "[4].ChildMenus[3].Name" $jsonContent[4].ChildMenus[3].Name;
WriteCsv $fileName "[4].ChildMenus[3].Icon" $jsonContent[4].ChildMenus[3].Icon;
WriteCsv $fileName "[4].ChildMenus[3].Function" $jsonContent[4].ChildMenus[3].Function;
WriteCsv $fileName "[4].ChildMenus[4].MenuId" $jsonContent[4].ChildMenus[4].MenuId;
WriteCsv $fileName "[4].ChildMenus[4].Name" $jsonContent[4].ChildMenus[4].Name;
WriteCsv $fileName "[4].ChildMenus[4].Icon" $jsonContent[4].ChildMenus[4].Icon;
WriteCsv $fileName "[4].ChildMenus[4].LinkParams[0]" $jsonContent[4].ChildMenus[4].LinkParams[0];
WriteCsv $fileName "[4].ChildMenus[4].LinkParams[1]" $jsonContent[4].ChildMenus[4].LinkParams[1];
WriteCsv $fileName "[4].ChildMenus[5].MenuId" $jsonContent[4].ChildMenus[5].MenuId;
WriteCsv $fileName "[4].ChildMenus[5].Name" $jsonContent[4].ChildMenus[5].Name;
WriteCsv $fileName "[4].ChildMenus[5].Icon" $jsonContent[4].ChildMenus[5].Icon;
WriteCsv $fileName "[4].ChildMenus[5].Function" $jsonContent[4].ChildMenus[5].Function;
$fileName = "Notification.json";
$jsonContent = ReadJsonContent($fileName);
WriteCsv $fileName "SecurityProtocolType" $jsonContent.SecurityProtocolType;
WriteCsv $fileName "Mail" $jsonContent.Mail;
WriteCsv $fileName "Slack" $jsonContent.Slack;
WriteCsv $fileName "ChatWork" $jsonContent.ChatWork;
WriteCsv $fileName "Line" $jsonContent.Line;
WriteCsv $fileName "Teams" $jsonContent.Teams;
WriteCsv $fileName "RocketChat" $jsonContent.RocketChat;
WriteCsv $fileName "InCircle" $jsonContent.InCircle;
WriteCsv $fileName "HttpClient" $jsonContent.HttpClient;
WriteCsv $fileName "CopyWithNotifications" $jsonContent.CopyWithNotifications;
WriteCsv $fileName "ListOrder" $jsonContent.ListOrder;
WriteCsv $fileName "HttpClientEncodings[0]" $jsonContent.HttpClientEncodings[0];
WriteCsv $fileName "HttpClientEncodings[1]" $jsonContent.HttpClientEncodings[1];
WriteCsv $fileName "HttpClientEncodings[2]" $jsonContent.HttpClientEncodings[2];
$fileName = "Parameter.json";
$jsonContent = ReadJsonContent($fileName);
WriteCsv $fileName "SqlParameterPrefix" $jsonContent.SqlParameterPrefix;
$fileName = "Permissions.json";
$jsonContent = ReadJsonContent($fileName);
WriteCsv $fileName "CheckManagePermission" $jsonContent.CheckManagePermission;
WriteCsv $fileName "General" $jsonContent.General;
WriteCsv $fileName "Manager" $jsonContent.Manager;
WriteCsv $fileName "Pattern.ReadOnly" $jsonContent.Pattern.ReadOnly;
WriteCsv $fileName "Pattern.ReadWrite" $jsonContent.Pattern.ReadWrite;
WriteCsv $fileName "Pattern.Leader" $jsonContent.Pattern.Leader;
WriteCsv $fileName "Pattern.Manager" $jsonContent.Pattern.Manager;
WriteCsv $fileName "PageSize" $jsonContent.PageSize;
WriteCsv $fileName "DeptFormat" $jsonContent.DeptFormat;
WriteCsv $fileName "GroupFormat" $jsonContent.GroupFormat;
WriteCsv $fileName "UserFormat" $jsonContent.UserFormat;
$fileName = "Rds.json";
$jsonContent = ReadJsonContent($fileName);
WriteCsv $fileName "Dbms" $jsonContent.Dbms;
WriteCsv $fileName "Provider" $jsonContent.Provider;
WriteCsv $fileName "SaConnectionString" $jsonContent.SaConnectionString;
WriteCsv $fileName "OwnerConnectionString" $jsonContent.OwnerConnectionString;
WriteCsv $fileName "UserConnectionString" $jsonContent.UserConnectionString;
WriteCsv $fileName "SqlCommandTimeOut" $jsonContent.SqlCommandTimeOut;
WriteCsv $fileName "MinimumTime" $jsonContent.MinimumTime;
WriteCsv $fileName "DeadlockRetryCount" $jsonContent.DeadlockRetryCount;
WriteCsv $fileName "DeadlockRetryInterval" $jsonContent.DeadlockRetryInterval;
WriteCsv $fileName "DisableIndexChangeDetection" $jsonContent.DisableIndexChangeDetection;
WriteCsv $fileName "SysLogsSchemaVersion" $jsonContent.SysLogsSchemaVersion;
$fileName = "Registration.json";
$jsonContent = ReadJsonContent($fileName);
WriteCsv $fileName "Enabled" $jsonContent.Enabled;
WriteCsv $fileName "PrivilegedUserOnly" $jsonContent.PrivilegedUserOnly;
WriteCsv $fileName "ApprovalRequestTo" $jsonContent.ApprovalRequestTo;
$fileName = "Reminder.json";
$jsonContent = ReadJsonContent($fileName);
WriteCsv $fileName "Enabled" $jsonContent.Enabled;
WriteCsv $fileName "Mail" $jsonContent.Mail;
WriteCsv $fileName "Slack" $jsonContent.Slack;
WriteCsv $fileName "ChatWork" $jsonContent.ChatWork;
WriteCsv $fileName "Line" $jsonContent.Line;
WriteCsv $fileName "Teams" $jsonContent.Teams;
WriteCsv $fileName "RocketChat" $jsonContent.RocketChat;
WriteCsv $fileName "InCircle" $jsonContent.InCircle;
WriteCsv $fileName "Interval" $jsonContent.Interval;
WriteCsv $fileName "Span" $jsonContent.Span;
WriteCsv $fileName "Limit" $jsonContent.Limit;
WriteCsv $fileName "DefaultLine" $jsonContent.DefaultLine;
WriteCsv $fileName "MinRange" $jsonContent.MinRange;
WriteCsv $fileName "MaxRange" $jsonContent.MaxRange;
WriteCsv $fileName "DefaultRange" $jsonContent.DefaultRange;
WriteCsv $fileName "CopyWithReminders" $jsonContent.CopyWithReminders;
WriteCsv $fileName "ListOrder" $jsonContent.ListOrder;
$fileName = "Script.json";
$jsonContent = ReadJsonContent($fileName);
WriteCsv $fileName "ServerScript" $jsonContent.ServerScript;
WriteCsv $fileName "DisableServerScriptHttpClient" $jsonContent.DisableServerScriptHttpClient;
WriteCsv $fileName "ServerScriptTimeOut" $jsonContent.ServerScriptTimeOut;
WriteCsv $fileName "ServerScriptTimeOutChangeable" $jsonContent.ServerScriptTimeOutChangeable;
WriteCsv $fileName "ServerScriptTimeOutMin" $jsonContent.ServerScriptTimeOutMin;
WriteCsv $fileName "ServerScriptTimeOutMax" $jsonContent.ServerScriptTimeOutMax;
WriteCsv $fileName "ServerScriptIncludeDepthLimit" $jsonContent.ServerScriptIncludeDepthLimit;
$fileName = "Search.json";
$jsonContent = ReadJsonContent($fileName);
WriteCsv $fileName "SearchDocuments" $jsonContent.SearchDocuments;
WriteCsv $fileName "CreateIndexes" $jsonContent.CreateIndexes;
WriteCsv $fileName "PageSize" $jsonContent.PageSize;
WriteCsv $fileName "DisableCrossSearch" $jsonContent.DisableCrossSearch;
WriteCsv $fileName "DisableCrossSearchSites" $jsonContent.DisableCrossSearchSites;
WriteCsv $fileName "FullTextIncludeBreadcrumb" $jsonContent.FullTextIncludeBreadcrumb;
WriteCsv $fileName "FullTextIncludeSiteId" $jsonContent.FullTextIncludeSiteId;
WriteCsv $fileName "FullTextIncludeSiteTitle" $jsonContent.FullTextIncludeSiteTitle;
WriteCsv $fileName "FullTextNumberOfMails" $jsonContent.FullTextNumberOfMails;
WriteCsv $fileName "FullTextMaxNumberOfMails" $jsonContent.FullTextMaxNumberOfMails;
$fileName = "Security.json";
$jsonContent = ReadJsonContent($fileName);
WriteCsv $fileName "AllowIpAddresses" $jsonContent.AllowIpAddresses;
WriteCsv $fileName "MimeTypeCheckOnApi" $jsonContent.MimeTypeCheckOnApi;
WriteCsv $fileName "PrivilegedUsers" $jsonContent.PrivilegedUsers;
WriteCsv $fileName "RevealUserDisabled" $jsonContent.RevealUserDisabled;
WriteCsv $fileName "LockoutCount" $jsonContent.LockoutCount;
WriteCsv $fileName "PasswordExpirationPeriod" $jsonContent.PasswordExpirationPeriod;
WriteCsv $fileName "JoeAccountCheck" $jsonContent.JoeAccountCheck;
WriteCsv $fileName "TokenCheck" $jsonContent.TokenCheck;
WriteCsv $fileName "SecureCookies" $jsonContent.SecureCookies;
WriteCsv $fileName "DisableMvcResponseHeader" $jsonContent.DisableMvcResponseHeader;
WriteCsv $fileName "DisableDeletingSiteAuthentication" $jsonContent.DisableDeletingSiteAuthentication;
WriteCsv $fileName "AccessControlAllowOrigin" $jsonContent.AccessControlAllowOrigin;
WriteCsv $fileName "EnforcePasswordHistories" $jsonContent.EnforcePasswordHistories;
WriteCsv $fileName "DisableCheckPasswordPolicyIfApi" $jsonContent.DisableCheckPasswordPolicyIfApi;
WriteCsv $fileName "PasswordPolicies[0].Enabled" $jsonContent.PasswordPolicies[0].Enabled;
WriteCsv $fileName "PasswordPolicies[0].Regex" $jsonContent.PasswordPolicies[0].Regex;
WriteCsv $fileName "PasswordPolicies[0].Languages[0].Body" $jsonContent.PasswordPolicies[0].Languages[0].Body;
WriteCsv $fileName "PasswordPolicies[0].Languages[1].Language" $jsonContent.PasswordPolicies[0].Languages[1].Language;
WriteCsv $fileName "PasswordPolicies[0].Languages[1].Body" $jsonContent.PasswordPolicies[0].Languages[1].Body;
WriteCsv $fileName "PasswordPolicies[1].Enabled" $jsonContent.PasswordPolicies[1].Enabled;
WriteCsv $fileName "PasswordPolicies[1].Regex" $jsonContent.PasswordPolicies[1].Regex;
WriteCsv $fileName "PasswordPolicies[1].Languages[0].Body" $jsonContent.PasswordPolicies[1].Languages[0].Body;
WriteCsv $fileName "PasswordPolicies[1].Languages[1].Language" $jsonContent.PasswordPolicies[1].Languages[1].Language;
WriteCsv $fileName "PasswordPolicies[1].Languages[1].Body" $jsonContent.PasswordPolicies[1].Languages[1].Body;
WriteCsv $fileName "PasswordPolicies[2].Enabled" $jsonContent.PasswordPolicies[2].Enabled;
WriteCsv $fileName "PasswordPolicies[2].Regex" $jsonContent.PasswordPolicies[2].Regex;
WriteCsv $fileName "PasswordPolicies[2].Languages[0].Body" $jsonContent.PasswordPolicies[2].Languages[0].Body;
WriteCsv $fileName "PasswordPolicies[2].Languages[1].Language" $jsonContent.PasswordPolicies[2].Languages[1].Language;
WriteCsv $fileName "PasswordPolicies[2].Languages[1].Body" $jsonContent.PasswordPolicies[2].Languages[1].Body;
WriteCsv $fileName "PasswordPolicies[3].Enabled" $jsonContent.PasswordPolicies[3].Enabled;
WriteCsv $fileName "PasswordPolicies[3].Regex" $jsonContent.PasswordPolicies[3].Regex;
WriteCsv $fileName "PasswordPolicies[3].Languages[0].Body" $jsonContent.PasswordPolicies[3].Languages[0].Body;
WriteCsv $fileName "PasswordPolicies[3].Languages[1].Language" $jsonContent.PasswordPolicies[3].Languages[1].Language;
WriteCsv $fileName "PasswordPolicies[3].Languages[1].Body" $jsonContent.PasswordPolicies[3].Languages[1].Body;
WriteCsv $fileName "PasswordPolicies[4].Enabled" $jsonContent.PasswordPolicies[4].Enabled;
WriteCsv $fileName "PasswordPolicies[4].Regex" $jsonContent.PasswordPolicies[4].Regex;
WriteCsv $fileName "PasswordPolicies[4].Languages[0].Body" $jsonContent.PasswordPolicies[4].Languages[0].Body;
WriteCsv $fileName "PasswordPolicies[4].Languages[1].Language" $jsonContent.PasswordPolicies[4].Languages[1].Language;
WriteCsv $fileName "PasswordPolicies[4].Languages[1].Body" $jsonContent.PasswordPolicies[4].Languages[1].Body;
WriteCsv $fileName "SecondaryAuthentication.Mode" $jsonContent.SecondaryAuthentication.Mode;
WriteCsv $fileName "SecondaryAuthentication.NotificationType" $jsonContent.SecondaryAuthentication.NotificationType;
WriteCsv $fileName "SecondaryAuthentication.NotificationMailBcc" $jsonContent.SecondaryAuthentication.NotificationMailBcc;
WriteCsv $fileName "SecondaryAuthentication.AuthenticationCodeCharacterType" $jsonContent.SecondaryAuthentication.AuthenticationCodeCharacterType;
WriteCsv $fileName "SecondaryAuthentication.AuthenticationCodeLength" $jsonContent.SecondaryAuthentication.AuthenticationCodeLength;
WriteCsv $fileName "SecondaryAuthentication.AuthenticationCodeExpirationPeriod" $jsonContent.SecondaryAuthentication.AuthenticationCodeExpirationPeriod;
WriteCsv $fileName "AspNetCoreDataProtection.BlobContainerUri" $jsonContent.AspNetCoreDataProtection.BlobContainerUri;
WriteCsv $fileName "AspNetCoreDataProtection.KeyIdentifier" $jsonContent.AspNetCoreDataProtection.KeyIdentifier;
WriteCsv $fileName "AspNetCoreDataProtection.KeyFileName" $jsonContent.AspNetCoreDataProtection.KeyFileName;
WriteCsv $fileName "HttpStrictTransportSecurity.Enabled" $jsonContent.HttpStrictTransportSecurity.Enabled;
WriteCsv $fileName "HttpStrictTransportSecurity.Preload" $jsonContent.HttpStrictTransportSecurity.Preload;
WriteCsv $fileName "HttpStrictTransportSecurity.IncludeSubDomains" $jsonContent.HttpStrictTransportSecurity.IncludeSubDomains;
WriteCsv $fileName "HttpStrictTransportSecurity.MaxAge" $jsonContent.HttpStrictTransportSecurity.MaxAge;
WriteCsv $fileName "HttpStrictTransportSecurity.ExcludeHosts" $jsonContent.HttpStrictTransportSecurity.ExcludeHosts;
WriteCsv $fileName "SecureCacheControl.NoCache" $jsonContent.SecureCacheControl.NoCache;
WriteCsv $fileName "SecureCacheControl.NoStore" $jsonContent.SecureCacheControl.NoStore;
WriteCsv $fileName "SecureCacheControl.Private" $jsonContent.SecureCacheControl.Private;
WriteCsv $fileName "SecureCacheControl.MustRevalidate" $jsonContent.SecureCacheControl.MustRevalidate;
WriteCsv $fileName "SecureCacheControl.PragmaNoCache" $jsonContent.SecureCacheControl.PragmaNoCache;
$fileName = "Service.json";
$jsonContent = ReadJsonContent($fileName);
WriteCsv $fileName "Name" $jsonContent.Name;
WriteCsv $fileName "TimeZoneDefault" $jsonContent.TimeZoneDefault;
WriteCsv $fileName "DefaultPassword" $jsonContent.DefaultPassword;
WriteCsv $fileName "DeploymentEnvironment" $jsonContent.DeploymentEnvironment;
WriteCsv $fileName "WithoutChangeDefaultPassword" $jsonContent.WithoutChangeDefaultPassword;
WriteCsv $fileName "DefaultLanguage" $jsonContent.DefaultLanguage;
WriteCsv $fileName "AbsoluteUri" $jsonContent.AbsoluteUri;
WriteCsv $fileName "MaxRequestBodySize" $jsonContent.MaxRequestBodySize;
WriteCsv $fileName "RequireHttps" $jsonContent.RequireHttps;
WriteCsv $fileName "AnnouncementSiteId" $jsonContent.AnnouncementSiteId;
WriteCsv $fileName "ShowProfiles" $jsonContent.ShowProfiles;
WriteCsv $fileName "ShowChangePassword" $jsonContent.ShowChangePassword;
WriteCsv $fileName "ShowStartGuide" $jsonContent.ShowStartGuide;
WriteCsv $fileName "Demo" $jsonContent.Demo;
WriteCsv $fileName "DemoUsagePeriod" $jsonContent.DemoUsagePeriod;
$fileName = "Session.json";
$jsonContent = ReadJsonContent($fileName);
WriteCsv $fileName "RetentionPeriod" $jsonContent.RetentionPeriod;
$fileName = "Site.json";
$jsonContent = ReadJsonContent($fileName);
WriteCsv $fileName "TopOrderBy" $jsonContent.TopOrderBy;
$fileName = "SitePackage.json";
$jsonContent = ReadJsonContent($fileName);
WriteCsv $fileName "Import" $jsonContent.Import;
WriteCsv $fileName "Export" $jsonContent.Export;
WriteCsv $fileName "ExportLimit" $jsonContent.ExportLimit;
WriteCsv $fileName "IncludeDataOnImport" $jsonContent.IncludeDataOnImport;
WriteCsv $fileName "IncludeSitePermissionOnImport" $jsonContent.IncludeSitePermissionOnImport;
WriteCsv $fileName "IncludeRecordPermissionOnImport" $jsonContent.IncludeRecordPermissionOnImport;
WriteCsv $fileName "IncludeColumnPermissionOnImport" $jsonContent.IncludeColumnPermissionOnImport;
WriteCsv $fileName "IncludeNotificationsOnImport" $jsonContent.IncludeNotificationsOnImport;
WriteCsv $fileName "IncludeRemindersOnImport" $jsonContent.IncludeRemindersOnImport;
WriteCsv $fileName "IncludeDataOnExport" $jsonContent.IncludeDataOnExport;
WriteCsv $fileName "UseIndentOptionOnExport" $jsonContent.UseIndentOptionOnExport;
WriteCsv $fileName "IncludeSitePermissionOnExport" $jsonContent.IncludeSitePermissionOnExport;
WriteCsv $fileName "IncludeRecordPermissionOnExport" $jsonContent.IncludeRecordPermissionOnExport;
WriteCsv $fileName "IncludeColumnPermissionOnExport" $jsonContent.IncludeColumnPermissionOnExport;
WriteCsv $fileName "IncludeNotificationsOnExport" $jsonContent.IncludeNotificationsOnExport;
WriteCsv $fileName "IncludeRemindersOnExport" $jsonContent.IncludeRemindersOnExport;
$fileName = "SysLog.json";
$jsonContent = ReadJsonContent($fileName);
WriteCsv $fileName "RetentionPeriod" $jsonContent.RetentionPeriod;
WriteCsv $fileName "NotLoggingIp" $jsonContent.NotLoggingIp;
WriteCsv $fileName "LoginSuccess" $jsonContent.LoginSuccess;
WriteCsv $fileName "LoginFailure" $jsonContent.LoginFailure;
WriteCsv $fileName "SignOut" $jsonContent.SignOut;
WriteCsv $fileName "ExportLimit" $jsonContent.ExportLimit;
$fileName = "User.json";
$jsonContent = ReadJsonContent($fileName);
WriteCsv $fileName "DisableTopSiteCreation" $jsonContent.DisableTopSiteCreation;
WriteCsv $fileName "DisableGroupAdmin" $jsonContent.DisableGroupAdmin;
WriteCsv $fileName "DisableGroupCreation" $jsonContent.DisableGroupCreation;
WriteCsv $fileName "DisableApi" $jsonContent.DisableApi;
WriteCsv $fileName "SelectorToolTip" $jsonContent.SelectorToolTip;
WriteCsv $fileName "Theme" $jsonContent.Theme;
$fileName = "Validation.json";
$jsonContent = ReadJsonContent($fileName);
WriteCsv $fileName "MaxLength" $jsonContent.MaxLength;
WriteCsv $fileName "MaxLengthCountType" $jsonContent.MaxLengthCountType;
WriteCsv $fileName "SingleByteCharactorRegexClient" $jsonContent.SingleByteCharactorRegexClient;
WriteCsv $fileName "SingleSyteCharactorRegexServer" $jsonContent.SingleSyteCharactorRegexServer;
$fileName = "Version.json";
$jsonContent = ReadJsonContent($fileName);
WriteCsv $fileName "ShowDeadline" $jsonContent.ShowDeadline;
WriteCsv $fileName "ShowLicensee" $jsonContent.ShowLicensee;
WriteCsv $fileName "ShowMaximumNumberOfUsers" $jsonContent.ShowMaximumNumberOfUsers;